//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public int id { get; set; }
        public string food_name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> expire { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string emp_name { get; set; }
        public Nullable<int> res_id { get; set; }
        public string res_name { get; set; }
        public string ordertime { get; set; }
        public string status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurent Restaurent { get; set; }
    }
}
